password = "hello"

emails = [
 "ahmadnaquibsyahmee",
 "balqis.hamzah@petronas.com",
 "balqis.hamzah@petronas.com.my",
 "adrina.salleh@petronas.com",
 "adrina.salleh@petronas.com.my",
 "afifi.ahmadsahimi@petronas.com",
 "afifi.ahmadsahimi@petronas.com.my",
 "ahmadhafiznaqiu.mwak@petronas.com",
 "ahmadhafiznaqiu.mwak@petronas.com.my",
 "ain.nasher@petronas.com",
 "ain.nasher@petronas.com.my",
 "ammar.abdullah@petronas.com",
 "ammar.abdullah@petronas.com",
 "arifah.yahya@petronas.com",
 "arifah.yahya@petronas.com.my",
 "benny.dwiastomo@petronas.com",
 "benny.dwiastomo@petronas.com.my",
 "candra.nugrah@petronas.com",
 "darrel.sudin@petronas.com",
 "darrel.sudin@petronas.com.my",
 "dzulfadli_ibrahim@petronas.com",
 "dzulfadli_ibrahim@petronas.com.my",
 "esmehasree.jamaludin@petronas.com",
 "esmehasree.jamaludin@petronas.com.my",
 "hafizuddin.abdrahm@petronas.com",
 "hamimie.mohamad@petronas.com",
 "hamimie.mohamad@petronas.com.my",
 "husaini.rasid@petronas.com",
 "husaini.rasid@petronas.com.my",
 "iqmalhakeem.badrulza@petronas.com",
 "iqmalhakeem.badrulza@petronas.com.my",
 "juzaili_kabri@petronas.com",
 "juzaili_kabri@petronas.com.my",
 "khairol.sulaiman@petronas.com",
 "khairol.sulaiman@petronas.com.my",
 "liew.xiaoting@petronas.com",
 "liew.xiaoting@petronas.com.my",
 "maimanhafiz.mnazri@petronas.com",
 "maimanhafiz.mnazri@petronas.com.my",
 "mazwan.azli@petronas.com",
 "mazwan.azli@petronas.com.my",
 "mhanafi.mohamadfaiz@petronas.com",
 "mhanafi.mohamadfaiz@petronas.com.my",
 "mhaziq.rozaim@petronas.com",
 "mhaziq.rozaim@petronas.com.my",
 "mjarisarif.johari@petronas.com",
 "mjarisarif.johari@petronas.com.my",
 "mraziemaiman.rozaidi@petronas.com",
 "mraziemaiman.rozaidi@petronas.com",
 "muhahac@petronas.com",
 "muhahac@petronas.com",
 "nazri_dzulkifli@petronas.com",
 "nazri_dzulkifli@petronas.com.my",
 "nurhasuna_khalid@petronas.com",
 "nurhasuna_khalid@petronas.com.my",
 "nurulaishah.abdrahm@petronas.com",
 "nurulaishah.abdrahm@petronas.com.my",
 "nurynqistina.norish@petronas.com",
 "nurynqistina.norish@petronas.com.my",
 "premkumar.paramasiv@petronas.com",
 "premkumar.paramasiv@petronas.com",
 "roziana.r@petronas.com",
 "roziana.r@petronas.com.my",
 "ruzanna.razali@petronas.com",
 "ruzanna.razali@petronas.com.my",
 "sitiaisyah.kamarul@petronas.com",
 "sitiaisyah.kamarul@petronas.com.my",
 "yusuf.theolbg@petronas.com",
 "yusuf.theolbg@petronas.com",
 "zariahbt.ismail@petronas.com",
 "zariahbt.ismail@petronas.com.my"
]


admin_emails = [ 
    "candra.nugrah@petronas.com.my",
    "hafizuddin.abdrahm@petronas.com.my",
    "ahmadnaquibsyahmee.m@petronas.com.my"
    "admincapexai@petronas.com"
    ]
